ALTER TYPE "CommercialTaxKind" ADD VALUE IF NOT EXISTS 'PPN_AND_PPH_4_2';
ALTER TYPE "CommercialTaxKind" ADD VALUE IF NOT EXISTS 'PPH_21';
ALTER TYPE "CommercialTaxKind" ADD VALUE IF NOT EXISTS 'PPH_22';
ALTER TYPE "CommercialTaxKind" ADD VALUE IF NOT EXISTS 'PPH_26';
ALTER TYPE "CommercialTaxKind" ADD VALUE IF NOT EXISTS 'STAMP_DUTY';

ALTER TABLE "Project" ADD COLUMN IF NOT EXISTS "otherTaxName" TEXT;
ALTER TABLE "PurchaseInvoice" ADD COLUMN IF NOT EXISTS "otherTaxName" TEXT;
