/** ITU E.164 dial codes for every country/territory (unsorted source). */
export type PhoneCountryEntry = {
  /** ISO 3166-1 alpha-2 (or XK for Kosovo). Unique Select value. */
  id: string;
  /** E.164 country calling code, e.g. "+62". */
  code: string;
  /** English country/territory name for alphabetical sorting. */
  label: string;
};

export const PHONE_COUNTRY_CODE_ENTRIES: PhoneCountryEntry[] = [
  { id: "AF", code: "+93", label: "Afghanistan" },
  { id: "AL", code: "+355", label: "Albania" },
  { id: "DZ", code: "+213", label: "Algeria" },
  { id: "AS", code: "+1", label: "American Samoa" },
  { id: "AD", code: "+376", label: "Andorra" },
  { id: "AO", code: "+244", label: "Angola" },
  { id: "AI", code: "+1", label: "Anguilla" },
  { id: "AG", code: "+1", label: "Antigua and Barbuda" },
  { id: "AR", code: "+54", label: "Argentina" },
  { id: "AM", code: "+374", label: "Armenia" },
  { id: "AW", code: "+297", label: "Aruba" },
  { id: "AU", code: "+61", label: "Australia" },
  { id: "AT", code: "+43", label: "Austria" },
  { id: "AZ", code: "+994", label: "Azerbaijan" },
  { id: "BS", code: "+1", label: "Bahamas" },
  { id: "BH", code: "+973", label: "Bahrain" },
  { id: "BD", code: "+880", label: "Bangladesh" },
  { id: "BB", code: "+1", label: "Barbados" },
  { id: "BY", code: "+375", label: "Belarus" },
  { id: "BE", code: "+32", label: "Belgium" },
  { id: "BZ", code: "+501", label: "Belize" },
  { id: "BJ", code: "+229", label: "Benin" },
  { id: "BM", code: "+1", label: "Bermuda" },
  { id: "BT", code: "+975", label: "Bhutan" },
  { id: "BO", code: "+591", label: "Bolivia" },
  { id: "BA", code: "+387", label: "Bosnia and Herzegovina" },
  { id: "BW", code: "+267", label: "Botswana" },
  { id: "BR", code: "+55", label: "Brazil" },
  { id: "IO", code: "+246", label: "British Indian Ocean Territory" },
  { id: "VG", code: "+1", label: "British Virgin Islands" },
  { id: "BN", code: "+673", label: "Brunei" },
  { id: "BG", code: "+359", label: "Bulgaria" },
  { id: "BF", code: "+226", label: "Burkina Faso" },
  { id: "BI", code: "+257", label: "Burundi" },
  { id: "KH", code: "+855", label: "Cambodia" },
  { id: "CM", code: "+237", label: "Cameroon" },
  { id: "CA", code: "+1", label: "Canada" },
  { id: "CV", code: "+238", label: "Cape Verde" },
  { id: "KY", code: "+1", label: "Cayman Islands" },
  { id: "CF", code: "+236", label: "Central African Republic" },
  { id: "TD", code: "+235", label: "Chad" },
  { id: "CL", code: "+56", label: "Chile" },
  { id: "CN", code: "+86", label: "China" },
  { id: "CX", code: "+61", label: "Christmas Island" },
  { id: "CC", code: "+61", label: "Cocos (Keeling) Islands" },
  { id: "CO", code: "+57", label: "Colombia" },
  { id: "KM", code: "+269", label: "Comoros" },
  { id: "CG", code: "+242", label: "Congo" },
  { id: "CK", code: "+682", label: "Cook Islands" },
  { id: "CR", code: "+506", label: "Costa Rica" },
  { id: "HR", code: "+385", label: "Croatia" },
  { id: "CU", code: "+53", label: "Cuba" },
  { id: "CW", code: "+599", label: "Curacao" },
  { id: "CY", code: "+357", label: "Cyprus" },
  { id: "CZ", code: "+420", label: "Czech Republic" },
  { id: "CD", code: "+243", label: "Democratic Republic of the Congo" },
  { id: "DK", code: "+45", label: "Denmark" },
  { id: "DJ", code: "+253", label: "Djibouti" },
  { id: "DM", code: "+1", label: "Dominica" },
  { id: "DO", code: "+1", label: "Dominican Republic" },
  { id: "TL", code: "+670", label: "East Timor" },
  { id: "EC", code: "+593", label: "Ecuador" },
  { id: "EG", code: "+20", label: "Egypt" },
  { id: "SV", code: "+503", label: "El Salvador" },
  { id: "GQ", code: "+240", label: "Equatorial Guinea" },
  { id: "ER", code: "+291", label: "Eritrea" },
  { id: "EE", code: "+372", label: "Estonia" },
  { id: "SZ", code: "+268", label: "Eswatini" },
  { id: "ET", code: "+251", label: "Ethiopia" },
  { id: "FK", code: "+500", label: "Falkland Islands" },
  { id: "FO", code: "+298", label: "Faroe Islands" },
  { id: "FJ", code: "+679", label: "Fiji" },
  { id: "FI", code: "+358", label: "Finland" },
  { id: "FR", code: "+33", label: "France" },
  { id: "GF", code: "+594", label: "French Guiana" },
  { id: "PF", code: "+689", label: "French Polynesia" },
  { id: "GA", code: "+241", label: "Gabon" },
  { id: "GM", code: "+220", label: "Gambia" },
  { id: "GE", code: "+995", label: "Georgia" },
  { id: "DE", code: "+49", label: "Germany" },
  { id: "GH", code: "+233", label: "Ghana" },
  { id: "GI", code: "+350", label: "Gibraltar" },
  { id: "GR", code: "+30", label: "Greece" },
  { id: "GL", code: "+299", label: "Greenland" },
  { id: "GD", code: "+1", label: "Grenada" },
  { id: "GP", code: "+590", label: "Guadeloupe" },
  { id: "GU", code: "+1", label: "Guam" },
  { id: "GT", code: "+502", label: "Guatemala" },
  { id: "GG", code: "+44", label: "Guernsey" },
  { id: "GN", code: "+224", label: "Guinea" },
  { id: "GW", code: "+245", label: "Guinea-Bissau" },
  { id: "GY", code: "+592", label: "Guyana" },
  { id: "HT", code: "+509", label: "Haiti" },
  { id: "HN", code: "+504", label: "Honduras" },
  { id: "HK", code: "+852", label: "Hong Kong" },
  { id: "HU", code: "+36", label: "Hungary" },
  { id: "IS", code: "+354", label: "Iceland" },
  { id: "IN", code: "+91", label: "India" },
  { id: "ID", code: "+62", label: "Indonesia" },
  { id: "IR", code: "+98", label: "Iran" },
  { id: "IQ", code: "+964", label: "Iraq" },
  { id: "IE", code: "+353", label: "Ireland" },
  { id: "IM", code: "+44", label: "Isle of Man" },
  { id: "IL", code: "+972", label: "Israel" },
  { id: "IT", code: "+39", label: "Italy" },
  { id: "CI", code: "+225", label: "Ivory Coast" },
  { id: "JM", code: "+1", label: "Jamaica" },
  { id: "JP", code: "+81", label: "Japan" },
  { id: "JE", code: "+44", label: "Jersey" },
  { id: "JO", code: "+962", label: "Jordan" },
  { id: "KZ", code: "+7", label: "Kazakhstan" },
  { id: "KE", code: "+254", label: "Kenya" },
  { id: "KI", code: "+686", label: "Kiribati" },
  { id: "XK", code: "+383", label: "Kosovo" },
  { id: "KW", code: "+965", label: "Kuwait" },
  { id: "KG", code: "+996", label: "Kyrgyzstan" },
  { id: "LA", code: "+856", label: "Laos" },
  { id: "LV", code: "+371", label: "Latvia" },
  { id: "LB", code: "+961", label: "Lebanon" },
  { id: "LS", code: "+266", label: "Lesotho" },
  { id: "LR", code: "+231", label: "Liberia" },
  { id: "LY", code: "+218", label: "Libya" },
  { id: "LI", code: "+423", label: "Liechtenstein" },
  { id: "LT", code: "+370", label: "Lithuania" },
  { id: "LU", code: "+352", label: "Luxembourg" },
  { id: "MO", code: "+853", label: "Macau" },
  { id: "MG", code: "+261", label: "Madagascar" },
  { id: "MW", code: "+265", label: "Malawi" },
  { id: "MY", code: "+60", label: "Malaysia" },
  { id: "MV", code: "+960", label: "Maldives" },
  { id: "ML", code: "+223", label: "Mali" },
  { id: "MT", code: "+356", label: "Malta" },
  { id: "MH", code: "+692", label: "Marshall Islands" },
  { id: "MQ", code: "+596", label: "Martinique" },
  { id: "MR", code: "+222", label: "Mauritania" },
  { id: "MU", code: "+230", label: "Mauritius" },
  { id: "YT", code: "+262", label: "Mayotte" },
  { id: "MX", code: "+52", label: "Mexico" },
  { id: "FM", code: "+691", label: "Micronesia" },
  { id: "MD", code: "+373", label: "Moldova" },
  { id: "MC", code: "+377", label: "Monaco" },
  { id: "MN", code: "+976", label: "Mongolia" },
  { id: "ME", code: "+382", label: "Montenegro" },
  { id: "MS", code: "+1", label: "Montserrat" },
  { id: "MA", code: "+212", label: "Morocco" },
  { id: "MZ", code: "+258", label: "Mozambique" },
  { id: "MM", code: "+95", label: "Myanmar" },
  { id: "NA", code: "+264", label: "Namibia" },
  { id: "NR", code: "+674", label: "Nauru" },
  { id: "NP", code: "+977", label: "Nepal" },
  { id: "NL", code: "+31", label: "Netherlands" },
  { id: "NC", code: "+687", label: "New Caledonia" },
  { id: "NZ", code: "+64", label: "New Zealand" },
  { id: "NI", code: "+505", label: "Nicaragua" },
  { id: "NE", code: "+227", label: "Niger" },
  { id: "NG", code: "+234", label: "Nigeria" },
  { id: "NU", code: "+683", label: "Niue" },
  { id: "NF", code: "+672", label: "Norfolk Island" },
  { id: "KP", code: "+850", label: "North Korea" },
  { id: "MK", code: "+389", label: "North Macedonia" },
  { id: "MP", code: "+1", label: "Northern Mariana Islands" },
  { id: "NO", code: "+47", label: "Norway" },
  { id: "OM", code: "+968", label: "Oman" },
  { id: "PK", code: "+92", label: "Pakistan" },
  { id: "PW", code: "+680", label: "Palau" },
  { id: "PS", code: "+970", label: "Palestine" },
  { id: "PA", code: "+507", label: "Panama" },
  { id: "PG", code: "+675", label: "Papua New Guinea" },
  { id: "PY", code: "+595", label: "Paraguay" },
  { id: "PE", code: "+51", label: "Peru" },
  { id: "PH", code: "+63", label: "Philippines" },
  { id: "PL", code: "+48", label: "Poland" },
  { id: "PT", code: "+351", label: "Portugal" },
  { id: "PR", code: "+1", label: "Puerto Rico" },
  { id: "QA", code: "+974", label: "Qatar" },
  { id: "RE", code: "+262", label: "Reunion" },
  { id: "RO", code: "+40", label: "Romania" },
  { id: "RU", code: "+7", label: "Russia" },
  { id: "RW", code: "+250", label: "Rwanda" },
  { id: "BL", code: "+590", label: "Saint Barthelemy" },
  { id: "SH", code: "+290", label: "Saint Helena" },
  { id: "KN", code: "+1", label: "Saint Kitts and Nevis" },
  { id: "LC", code: "+1", label: "Saint Lucia" },
  { id: "MF", code: "+590", label: "Saint Martin" },
  { id: "PM", code: "+508", label: "Saint Pierre and Miquelon" },
  { id: "VC", code: "+1", label: "Saint Vincent and the Grenadines" },
  { id: "WS", code: "+685", label: "Samoa" },
  { id: "SM", code: "+378", label: "San Marino" },
  { id: "ST", code: "+239", label: "Sao Tome and Principe" },
  { id: "SA", code: "+966", label: "Saudi Arabia" },
  { id: "SN", code: "+221", label: "Senegal" },
  { id: "RS", code: "+381", label: "Serbia" },
  { id: "SC", code: "+248", label: "Seychelles" },
  { id: "SL", code: "+232", label: "Sierra Leone" },
  { id: "SG", code: "+65", label: "Singapore" },
  { id: "SX", code: "+1", label: "Sint Maarten" },
  { id: "SK", code: "+421", label: "Slovakia" },
  { id: "SI", code: "+386", label: "Slovenia" },
  { id: "SB", code: "+677", label: "Solomon Islands" },
  { id: "SO", code: "+252", label: "Somalia" },
  { id: "ZA", code: "+27", label: "South Africa" },
  { id: "KR", code: "+82", label: "South Korea" },
  { id: "SS", code: "+211", label: "South Sudan" },
  { id: "ES", code: "+34", label: "Spain" },
  { id: "LK", code: "+94", label: "Sri Lanka" },
  { id: "SD", code: "+249", label: "Sudan" },
  { id: "SR", code: "+597", label: "Suriname" },
  { id: "SJ", code: "+47", label: "Svalbard and Jan Mayen" },
  { id: "SE", code: "+46", label: "Sweden" },
  { id: "CH", code: "+41", label: "Switzerland" },
  { id: "SY", code: "+963", label: "Syria" },
  { id: "TW", code: "+886", label: "Taiwan" },
  { id: "TJ", code: "+992", label: "Tajikistan" },
  { id: "TZ", code: "+255", label: "Tanzania" },
  { id: "TH", code: "+66", label: "Thailand" },
  { id: "TG", code: "+228", label: "Togo" },
  { id: "TK", code: "+690", label: "Tokelau" },
  { id: "TO", code: "+676", label: "Tonga" },
  { id: "TT", code: "+1", label: "Trinidad and Tobago" },
  { id: "TN", code: "+216", label: "Tunisia" },
  { id: "TR", code: "+90", label: "Turkey" },
  { id: "TM", code: "+993", label: "Turkmenistan" },
  { id: "TC", code: "+1", label: "Turks and Caicos Islands" },
  { id: "TV", code: "+688", label: "Tuvalu" },
  { id: "UG", code: "+256", label: "Uganda" },
  { id: "UA", code: "+380", label: "Ukraine" },
  { id: "AE", code: "+971", label: "United Arab Emirates" },
  { id: "GB", code: "+44", label: "United Kingdom" },
  { id: "US", code: "+1", label: "United States" },
  { id: "VI", code: "+1", label: "United States Virgin Islands" },
  { id: "UY", code: "+598", label: "Uruguay" },
  { id: "UZ", code: "+998", label: "Uzbekistan" },
  { id: "VU", code: "+678", label: "Vanuatu" },
  { id: "VA", code: "+39", label: "Vatican City" },
  { id: "VE", code: "+58", label: "Venezuela" },
  { id: "VN", code: "+84", label: "Vietnam" },
  { id: "WF", code: "+681", label: "Wallis and Futuna" },
  { id: "EH", code: "+212", label: "Western Sahara" },
  { id: "YE", code: "+967", label: "Yemen" },
  { id: "ZM", code: "+260", label: "Zambia" },
  { id: "ZW", code: "+263", label: "Zimbabwe" },
];
